[project]
name = "videotoslides"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "img2pdf>=0.5.1",
    "opencv-python-headless>=4.10.0.84",
]
